name: django

services:
  adminer:
    image: adminer:5
    restart: always
    ports:
      - 9999:8080

  db:
    image: postgres:18
    environment:
      POSTGRES_DB: django_playground
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql

  web:
    image: django-playground
    ports:
      - 8888:8000
    env_file:
      - .env.docker
    depends_on:
      - db

volumes:
  postgres_data: