# Generated by Django 5.2.8 on 2026-01-10 05:26

import blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_article_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/covers/', validators=[blog.validators.validate_image_size, blog.validators.validate_image_extension, blog.validators.validate_image_dimensions]),
        ),
    ]
